# Generated by Django 5.2.4 on 2025-07-31 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quotation_no', models.PositiveIntegerField(unique=True)),
                ('module_quantity', models.PositiveIntegerField()),
                ('module_wp', models.PositiveIntegerField()),
                ('inverter_size', models.FloatField(help_text='in kW')),
                ('complete_epc_rate', models.FloatField()),
                ('meter_charge', models.FloatField(default=3350)),
                ('fabrication_rate', models.FloatField(default=4000)),
                ('module_rate', models.FloatField()),
                ('inverter_rate', models.FloatField()),
                ('gst_percent', models.FloatField(default=12.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
